project:
  type: website
  render:
  - '*.qmd'
  - '*.ipynb'
  - examples/*.ipynb
  - pages/*.qmd
  resources:
  - assets/*
  - authors.yml
  - CITATION.cff
execute:
  freeze: auto
website:
  favicon: assets/logo_white.png
  twitter-card: true
  open-graph: true
  navbar:
    collapse-below: xl
    pinned: false
    title: false
    left:
    - text: '{{< iconify qlementine-icons:version-control-16 >}}'
      menu:
      - text: v1.09 (latest)
        href: index.ipynb
      - text: v1.08
        href: index_v1.08.ipynb
      - text: v1.07
        href: index_v1.07.ipynb
      - text: v1.06
        href: index_v1.06.ipynb
      - text: v1.05
        href: index_v1.05.ipynb
      - text: v1.04
        href: index_v1.04.ipynb
      - text: v1.03
        href: index_v1.03.ipynb
      - text: v1.01
        href: index_v1.01.ipynb
      - text: v1.0
        href: index_v1.0.ipynb
      - text: '1.02'
        href: index_1.02.ipynb
    - text: '{{< iconify nrk:back >}} Back to Pub'
      href: index.ipynb
    right:
    - text: FAQ
      href: pages/FAQ.qmd
    - text: Reproduce this pub
      href: pages/SETUP.qmd
    - text: Cite this pub
      href: '#'
    - text: Contribute
      href: pages/CONTRIBUTING.qmd
    tools:
    - icon: twitter-x
      href: https://twitter.com/arcadiascience
    - icon: github
      href: https://github.com/{{< var pub.org >}}/{{< var pub.repo >}}
    logo: assets/logo_text.png
    logo-href: https://research.arcadiascience.com/
    background: white
    search: true
  page-footer:
    background: '#484B50'
    border: false
    left: '[![](/assets/logo_white.png){fig-alt="Arcadia-Science" width=65px}](https://www.arcadiascience.com/)

      Copyright 2025, Arcadia Science

      '
    right:
    - icon: twitter-x
      href: https://twitter.com/arcadiascience
    - icon: github
      href: https://github.com/Arcadia-Science
  google-analytics: '{{< var pub.google_analytics_id >}}'
  cookie-consent:
    type: implied
    style: simple
format:
  html:
    html-math-method: katex
    include-in-header:
    - file: assets/logo-animation.html
    - file: assets/author-reveal.html
    - file: assets/mini-title.html
    - file: assets/version-in-title.html
    - file: assets/citation-box.html
    css:
    - assets/css/main.css
    - assets/css/citation-box.css
    page-layout: article
    title-block-banner: true
    toc: true
    toc-expand: 2
comments:
  giscus:
    repo: Arcadia-Science/glass-box-umap-notebook-pub
    input-position: top
reference-location: margin
bibliography: ref.bib
csl: assets/arcadia.csl
code-annotations: hover
html-table-processing: none
demo-title: A brief syntax demo
filters:
- abstract-section
- collapse-output
